# Generated by Django 5.1.1 on 2024-09-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок задачи ')),
                ('description', models.TextField(verbose_name='Описание для задачи')),
                ('completed', models.BooleanField(blank=True, default=False, null=True, verbose_name='ВЫполнено')),
                ('created', models.DateTimeField(verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
