# Generated by Django 5.1.1 on 2024-09-14 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_task_post_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
